import type { Project, Service, Article } from '@/lib/types'

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Highpeak Residence',
    slug: 'highpeak-residence',
    heroImage: '/images/project-residence.jpg',
    heroImageAlt: 'White residential tower with stacked terraces, seen from below',
    category: 'residential',
    location: 'Nairobi, Kenya',
    year: 2024,
    status: 'completed',
    description: 'A contemporary residential project showcasing modern architectural principles with sustainable design practices.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Tech Hub Office Complex',
    slug: 'tech-hub-office-complex',
    heroImage: '/images/project-office.jpg',
    heroImageAlt: 'Glass office towers seen from street level',
    category: 'commercial',
    location: 'Westlands, Nairobi',
    year: 2023,
    status: 'completed',
    description: 'A modern office complex designed for technology companies, featuring flexible workspaces and sustainable features.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2023-06-20'),
  },
  {
    id: '3',
    title: 'Cultural Center',
    slug: 'cultural-center',
    heroImage: '/images/project-cultural.jpg',
    heroImageAlt: 'Sculptural white concrete building against a dark sky',
    category: 'institutional',
    location: 'Nairobi, Kenya',
    year: 2024,
    status: 'in-progress',
    description: 'An institutional project dedicated to preserving and showcasing local cultural heritage through contemporary architecture.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    title: 'Boutique Hotel',
    slug: 'boutique-hotel',
    heroImage: '/images/project-hotel.jpg',
    heroImageAlt: 'Whitewashed terrace with a clay urn and a domed tower above the sea',
    category: 'hospitality',
    location: 'Kilifi, Kenya',
    year: 2023,
    status: 'completed',
    description: 'A luxury hospitality project combining contemporary design with local architectural traditions.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2023-09-05'),
    updatedAt: new Date('2023-09-05'),
  },
  {
    id: '5',
    title: 'Residential Estate Master Plan',
    slug: 'residential-estate-master-plan',
    heroImage: '/images/project-masterplan.jpg',
    heroImageAlt: 'Aerial view of green tea fields planted in rows',
    category: 'residential',
    location: 'Limuru, Kenya',
    year: 2024,
    status: 'planning',
    description: 'A comprehensive master plan for a sustainable residential estate integrating nature with modern living.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '6',
    title: 'Mixed-Use Development',
    slug: 'mixed-use-development',
    heroImage: '/images/project-mixed-use.jpg',
    heroImageAlt: 'Corner of a timber-clad building against a pale sky',
    category: 'commercial',
    location: 'Nairobi CBD',
    year: 2024,
    status: 'in-progress',
    description: 'An integrated mixed-use development combining retail, residential, and office spaces in an urban setting.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },
]

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'Architectural Design',
    slug: 'architectural-design',
    heroImage: '/images/service-design.jpg',
    heroImageAlt: 'Architectural drawings and drafting tools on a desk',
    description: 'Comprehensive architectural design services from concept development to detailed drawings and specifications.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Urban Planning',
    slug: 'urban-planning',
    heroImage: '/images/service-planning.jpg',
    heroImageAlt: 'Aerial view of a city grid',
    description: 'Strategic urban planning and master planning services for developments of all scales.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Sustainability Consulting',
    slug: 'sustainability-consulting',
    heroImage: '/images/service-sustainability.jpg',
    heroImageAlt: 'Bamboo forest seen from below',
    description: 'Expert guidance on sustainable design practices and environmental impact assessment.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Project Management',
    slug: 'project-management',
    heroImage: '/images/service-management.jpg',
    heroImageAlt: 'Steel structure seen from below',
    description: 'Full project management services ensuring timely and cost-effective delivery.',
    chatbotVisible: true,
    published: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'The Future of Sustainable Architecture in East Africa',
    slug: 'future-sustainable-architecture',
    coverImage: '/images/journal-sustainable.jpg',
    coverImageAlt: 'Balcony with fresh flowers and trees beyond',
    excerpt: 'Exploring how contemporary design principles can integrate with environmental stewardship in the African context.',
    body: 'This is a comprehensive article exploring the future of sustainable architecture in East Africa.',
    author: 'Highpeak Team',
    category: 'Sustainability',
    publishedAt: new Date('2024-09-15'),
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: '2',
    title: 'Contemporary Office Design Trends',
    slug: 'contemporary-office-design',
    coverImage: '/images/journal-office.jpg',
    coverImageAlt: 'Bright room with a wooden table and white chairs',
    excerpt: 'How modern workplaces are evolving to support flexible working and employee wellbeing.',
    body: 'This article discusses the latest trends in contemporary office design and their impact on productivity.',
    author: 'Highpeak Team',
    category: 'Design',
    publishedAt: new Date('2024-08-20'),
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-08-20'),
  },
  {
    id: '3',
    title: 'Preserving Cultural Heritage Through Architecture',
    slug: 'preserving-cultural-heritage',
    coverImage: '/images/journal-heritage.jpg',
    coverImageAlt: 'Stone cloister with arches lit by afternoon sun',
    excerpt: 'How architectural design can honor and celebrate local cultural traditions while embracing modernity.',
    body: 'An exploration of how contemporary architecture can respectfully integrate cultural heritage.',
    author: 'Highpeak Team',
    category: 'Culture',
    publishedAt: new Date('2024-07-10'),
    chatbotVisible: true,
    published: true,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-07-10'),
  },
]
